### ISSUE TITLE
need more instructions.

### ISSUE THREAD

**Issue by StellarStoic** [dodo-saba/fit2gpx#5]
Hi
Since I'm not a programmer but I do know how to follow instructions I'm stuck at yours. How exactly can I achieve converting a bunch of FIT files in a directory? 

I'm confused about where to put code from the instructions.

**Comment by dodo-saba** [comment]
Hi SimplePotato (username checks out),

The code from the instructions is all you need. You can simply execute the following (after replacing the directory path) and it will be done:

`from fit2gpx import Converter
conv = Converter()          # create standard converter object
conv.fit_to_gpx_bulk(dir_in='_<enter_path_to_directory>_', dir_out='./project/activities_convert/')
`

The only thing you need to change is the `dir_in` variable, which should be a string pointing to the path of the directory containing your FIT files. Hope this helps!

**Comment by StellarStoic** [comment]
700 fit files converted in 0.57 sec. That's crazy how much time this tool saved me 🤯 Thanks @dodo-saba

I found out what my issue was...
I could not get setup.py to work and I had to install (pandas, gpxpy and fitdecode) modules manually with pip3.
